name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: SaraBrito-developer
          
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark
